services:
  db:
    image: postgres
    container_name: helpdesk_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: helpdesk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
